begin;
select plan(56);
select extensions.ok(to_regclass('public.promotion_recommendation_snapshots') is not null, 'recommendation snapshots table exists');
select extensions.ok(to_regclass('public.student_progressions') is not null, 'progressions table exists');
select extensions.ok(to_regclass('public.promotion_decisions') is not null, 'decisions table exists');
select extensions.ok(to_regprocedure('internal.current_promotion_reader()') is not null, 'reader helper exists');
select extensions.ok(to_regprocedure('internal.require_promotion_reader()') is not null, 'reader guard exists');
select extensions.ok(to_regprocedure('internal.current_promotion_actor()') is not null, 'actor helper exists');
select extensions.ok(to_regprocedure('internal.require_promotion_actor()') is not null, 'actor guard exists');
select extensions.ok(to_regprocedure('internal.resolve_promotion_rule(uuid,uuid,uuid)') is not null, 'rule resolver exists');
select extensions.ok(to_regprocedure('internal.promotion_snapshot_for(uuid,uuid,uuid)') is not null, 'snapshot builder exists');
select extensions.ok(to_regprocedure('public.list_promotion_scopes()') is not null, 'scope RPC exists');
select extensions.ok(to_regprocedure('public.generate_promotion_recommendations(uuid,uuid)') is not null, 'generation RPC exists');
select extensions.ok(to_regprocedure('public.confirm_promotion_decision(uuid,integer,public.promotion_outcome,text)') is not null, 'versioned confirmation RPC exists');
select extensions.ok(to_regprocedure('public.reopen_promotion_decision(uuid,integer,text)') is not null, 'versioned reopen RPC exists');
select extensions.ok(to_regprocedure('public.apply_student_progression(uuid,integer,uuid,uuid)') is not null, 'versioned progression RPC exists');
select extensions.ok(to_regprocedure('public.list_promotion_decision_history(uuid)') is not null, 'history RPC exists');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='promotion_recommendation_snapshots' and column_name='snapshot_checksum'), 'snapshot checksum exists');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='promotion_recommendation_snapshots' and column_name='snapshot_data'), 'snapshot evidence exists');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='promotion_decisions' and column_name='version'), 'decision version exists');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='promotion_decisions' and column_name='superseded_by'), 'decision supersession exists');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='promotion_decisions' and column_name='recommendation_snapshot_id'), 'decision snapshot link exists');
select extensions.ok(exists(select 1 from pg_indexes where indexname='promotion_decision_one_current_idx'), 'one-current partial index exists');
select extensions.ok(exists(select 1 from pg_indexes where indexname='promotion_decision_term_enrollment_version_unique'), 'version uniqueness exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_recommendation_snapshots_prevent_mutation'), 'snapshot append-only trigger exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_recommendation_snapshots_validate_scope'), 'snapshot school scope trigger exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='student_progressions_prevent_mutation'), 'progression append-only trigger exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_decisions_stage17_validate'), 'decision immutability trigger exists');
select extensions.ok(has_function_privilege('anon', 'public.list_promotion_scopes()', 'EXECUTE') = false, 'anon cannot execute scope RPC');
select extensions.ok(has_function_privilege('public', 'public.list_promotion_scopes()', 'EXECUTE') = false, 'PUBLIC cannot execute scope RPC');
select extensions.ok(has_function_privilege('authenticated', 'public.list_promotion_scopes()', 'EXECUTE'), 'authenticated can read scope RPC');
select extensions.ok(has_function_privilege('authenticated', 'public.generate_promotion_recommendations(uuid,uuid)', 'EXECUTE'), 'authenticated can call generation RPC');
select extensions.ok(has_function_privilege('authenticated', 'public.confirm_promotion_decision(uuid,integer,public.promotion_outcome,text)', 'EXECUTE'), 'authenticated can call versioned confirmation RPC');
select extensions.ok(has_function_privilege('authenticated', 'public.apply_student_progression(uuid,integer,uuid,uuid)', 'EXECUTE'), 'authenticated can call versioned progression RPC');
select extensions.ok(has_table_privilege('authenticated', 'public.promotion_recommendation_snapshots', 'SELECT') = false, 'authenticated cannot select snapshots directly');
select extensions.ok(has_table_privilege('authenticated', 'public.promotion_recommendation_snapshots', 'INSERT') = false, 'authenticated cannot insert snapshots directly');
select extensions.ok(has_table_privilege('authenticated', 'public.student_progressions', 'UPDATE') = false, 'authenticated cannot update progressions directly');
select extensions.ok((select relrowsecurity from pg_class where oid='public.promotion_recommendation_snapshots'::regclass), 'snapshots use RLS');
select extensions.ok((select relforcerowsecurity from pg_class where oid='public.promotion_recommendation_snapshots'::regclass), 'snapshots force RLS');
select extensions.ok((select relrowsecurity from pg_class where oid='public.student_progressions'::regclass), 'progressions use RLS');
select extensions.ok((select relforcerowsecurity from pg_class where oid='public.student_progressions'::regclass), 'progressions force RLS');
select extensions.ok((select proconfig @> array['search_path=pg_catalog, public, internal'] from pg_proc where oid='public.confirm_promotion_decision(uuid,integer,public.promotion_outcome,text)'::regprocedure), 'confirmation has fixed search path');
select extensions.ok(not exists(select 1 from information_schema.role_table_grants where table_name in ('guardians','student_guardians','student_access_credentials','parent_access_sessions') and grantee='authenticated' and privilege_type in ('SELECT','INSERT','UPDATE','DELETE')), 'parent tables remain ungranted');
select extensions.ok(to_regprocedure('public.confirm_promotion_decision(uuid,public.promotion_outcome,text)') is null, 'obsolete confirmation signature removed');
select extensions.ok(to_regprocedure('public.reopen_promotion_decision(uuid,text)') is null, 'obsolete reopen signature removed');
select extensions.ok(to_regprocedure('public.apply_student_progression(uuid,uuid,uuid)') is null, 'obsolete progression signature removed');
select extensions.ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='student_progressions' and column_name='application_snapshot'), 'application snapshot column exists');
select extensions.ok(exists(select 1 from pg_constraint where conname='student_progression_application_snapshot_object'), 'application snapshot object constraint exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='student_progressions_validate_application'), 'application snapshot validation trigger exists');
select extensions.ok(exists(select 1 from pg_proc where proname='promotion_additional_rule_values' and prosecdef), 'additional rule parser exists');
select extensions.ok(not exists(select 1 from pg_proc where proname='promotion_additional_rule_values' and proacl is null), 'additional rule parser has explicit ACL');
select extensions.ok(pg_get_functiondef('internal.validate_promotion_additional_rules(public.promotion_rules)'::regprocedure) !~* 'allow_manual_review|require_all_required_subjects', 'obsolete additional rule keys are not accepted');
select extensions.ok(pg_get_functiondef('internal.promotion_snapshot_for(uuid,uuid,uuid)'::regprocedure) ~* 'days_open > 0', 'attendance positive-day branch is explicit');
select extensions.ok(pg_get_functiondef('internal.promotion_snapshot_for(uuid,uuid,uuid)'::regprocedure) ~* 'ACADEMIC_REVIEW', 'snapshot builder has conservative review outcome');
select extensions.ok(pg_get_functiondef('public.apply_student_progression(uuid,integer,uuid,uuid)'::regprocedure) ~* 'PROMOTION_PROGRESSION_OUTCOME_INVALID', 'unsupported progression outcomes fail closed');
select extensions.ok(pg_get_functiondef('public.apply_student_progression(uuid,integer,uuid,uuid)'::regprocedure) ~* 'year.status in .ACTIVE., .DRAFT.', 'progression restricts target year status');
select extensions.ok(pg_get_functiondef('public.apply_student_progression(uuid,integer,uuid,uuid)'::regprocedure) ~* 'source_year.ends_on', 'progression uses source academic-year lifecycle date');
select extensions.ok(pg_get_functiondef('public.list_promotion_recommendations(uuid,uuid)'::regprocedure) ~* 'CONFIRMED_STALE', 'confirmed stale state is exposed');
select * from extensions.finish();
rollback;
