begin;
select plan(30);
select extensions.ok(to_regclass('public.promotion_recommendation_snapshots') is not null, 'fixture schema is available');
select extensions.ok(to_regclass('public.student_progressions') is not null, 'progression fixture schema is available');
select extensions.ok(exists(select 1 from pg_indexes where indexname='promotion_decision_one_current_idx'), 'current-row invariant is installed');
select extensions.ok(exists(select 1 from pg_constraint where conname='promotion_decision_term_enrollment_version_unique'), 'version fixture invariant is installed');
select extensions.ok(exists(select 1 from pg_constraint where conname='promotion_snapshot_term_enrollment_run_unique'), 'snapshot determinism invariant is installed');
select extensions.ok(exists(select 1 from pg_constraint where conname='student_progression_source_unique'), 'progression idempotency invariant is installed');
select extensions.ok(exists(select 1 from pg_constraint where conname='student_progression_target_consistent'), 'completion target invariant is installed');
select extensions.ok(to_regprocedure('internal.analytics_run_is_current(uuid,uuid)') is not null, 'accepted current-result helper is used');
select extensions.ok(to_regprocedure('internal.results_input_checksum(uuid,uuid,uuid,uuid,uuid)') is not null, 'accepted checksum helper is available');
select extensions.ok(to_regprocedure('public.list_promotion_recommendations(uuid,uuid)') is not null, 'recommendation read fixture is available');
select extensions.ok(to_regprocedure('public.list_promotion_target_classes(uuid)') is not null, 'target-class fixture is available');
select extensions.ok((select count(*) from pg_enum where enumtypid='public.promotion_outcome'::regtype and enumlabel='REPEAT_RECOMMENDED')=1, 'recommendation repeat outcome exists');
select extensions.ok((select count(*) from pg_enum where enumtypid='public.promotion_outcome'::regtype and enumlabel='REPEAT_CONFIRMED')=1, 'human repeat outcome exists');
select extensions.ok((select count(*) from pg_enum where enumtypid='public.promotion_outcome'::regtype and enumlabel='COMPLETED')=1, 'completion outcome exists');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_decisions_validate_scope'), 'promotion scope trigger remains');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_decisions_stage17_validate'), 'promotion outcome restrictions remain');
select extensions.ok(exists(select 1 from pg_trigger where tgname='promotion_recommendation_snapshots_prevent_mutation'), 'snapshot immutability remains');
select extensions.ok(exists(select 1 from pg_trigger where tgname='student_progressions_validate_scope'), 'progression school scope remains');
select extensions.ok(exists(select 1 from pg_proc where proname='generate_promotion_recommendations' and prosecdef), 'generation is definer-bound');
select extensions.ok(exists(select 1 from pg_proc where proname='confirm_promotion_decision' and prosecdef), 'confirmation is definer-bound');
select extensions.ok(exists(select 1 from pg_proc where proname='apply_student_progression' and prosecdef), 'progression is definer-bound');
select extensions.ok(not exists(select 1 from pg_proc where proname='generate_promotion_recommendations' and prosrc ilike '%calculate_grade_results%'), 'generation does not calculate results');
select extensions.ok(not exists(select 1 from pg_proc where proname='confirm_promotion_decision' and prosrc ilike '%calculate_grade_results%'), 'confirmation does not calculate results');
select extensions.ok(not exists(select 1 from pg_proc where proname='apply_student_progression' and prosrc ilike '%calculate_grade_results%'), 'progression does not calculate results');
select extensions.ok(exists(select 1 from pg_indexes where indexname='enrollment_one_current_per_student_idx'), 'source/target lifecycle invariant exists');
select extensions.ok(exists(select 1 from pg_class where relname='promotion_decisions' and relrowsecurity), 'decision RLS remains enabled');
select extensions.ok(exists(select 1 from pg_class where relname='promotion_decisions' and relforcerowsecurity), 'decision RLS remains forced');
select extensions.ok((select count(*) from pg_proc where proname='list_promotion_decision_history')=1, 'history is a single deterministic reader');
select extensions.ok((select count(*) from pg_proc where proname='list_promotion_scopes')=1, 'scope is a single deterministic reader');
select extensions.ok(exists(select 1 from pg_constraint where conname='promotion_decision_snapshot_fk'), 'decision evidence is required for new workflow rows');
select * from extensions.finish();
rollback;
